### ISSUE TITLE
[android] default mode should be full integration instead of observe

### ISSUE THREAD

**Issue by kyoz** [Cap-go/capacitor-purchases#10]
Normally we using RevenueCat with Full Integration (default) mode, so I think I'll make sense if we make this mode as default.

On iOS it's seem default mode is full integration already but on [Android](https://github.com/Cap-go/capacitor-purchases/blob/main/android/src/main/java/ee/forgr/plugin/capacitor_purchases/CapacitorPurchasesPlugin.java#L42), it's using observe mode.

I do think we need an option for setup function.

**Comment by riderx** [comment]
@kyoz thanks for the report i have to check it more, the goal on android and ios is to use they new bridge everywhere, that will maybe solve it

**Comment by riderx** [comment]
with https://github.com/Cap-go/capacitor-purchases/issues/6 and 
https://github.com/Cap-go/capacitor-purchases/issues/7

**Comment by kyoz** [comment]
Thanks @riderx for your hard work. I'm new to Revenue Cat so doesn't know much. For now i'v just modify configuration code in java plugin to disable observe mode.

I'll test it when new version is released.

**Comment by aboedo** [comment]
I made https://github.com/Cap-go/capacitor-purchases/pull/12 with a potential fix

**Comment by riderx** [comment]
thanks a lot for this work i will try to have a look this week !

**Comment by riderx** [comment]
That have been merged ! and released in `1.3.17`

**Comment by aboedo** [comment]
Awesome! Thanks for the quick turnaround in review and releasing!

**Comment by riderx** [comment]
@aboedo found one issue in IOS i did send a fix
