### ISSUE TITLE
Add support for android subscription switching

### ISSUE THREAD

**Issue by SergenN** [Cap-go/capacitor-purchases#13]
The Cordova plugin uses the oldSku to allow users to change subscriptions. Even though this package has the struct for this functionality unfortunately it's not being used.

**Comment by riderx** [comment]
Hey @SergenN thanks for the feedback i'm not sure to understand what you mean, could you point me to the code or the doc of the cordova one  ?

**Comment by riderx** [comment]
oh, ok thanks! i added it !
