### ISSUE TITLE
Create quickstart guide or tutorial for newcomers

### ISSUE THREAD

**Issue by Nikita-schetko** [Cap-go/capacitor-purchases#14]
Hey guys! Thank for your product; I'm newbie in dealing with RevenueCat and ios InAppPurchases; It would be very helpful, if you give an example of a quickstart of your app;
Thank you in advance

**Comment by JanPhill** [comment]
Yes please, totally agree, that would be really awesome!!

**Comment by riderx** [comment]
Hey sorry for the delay i just did it this week : https://capgo.app/blog/in-app-purchases-capacitor/
