### ISSUE TITLE
`CapacitorPurchases.setup` never resolves on Android devices

### ISSUE THREAD

**Issue by arbassic** [Cap-go/capacitor-purchases#34]
Hi Cap-go!

The plugin is cool! Comparing to the old Cordova one it has lightweight interface and after a bit of struggling with RevCat (and the issue below) everything works just like a breeze!

However I noticed an issue with the `CapacitorPurchases.setup` method, which in fact never resolves when run on Android devices.

**Actual workaround** is simply not to await the method call... and IAPs work well. So it looks like there's a bug on the Android implementation side and some internal callbacks are not handled correctly, maybe?

It would be awesome, especially for newcomers, to have the function working well!

**Comment by riderx** [comment]
Hey @arbassic thanks for the feedback, did you tried the [2.0.15](https://github.com/Cap-go/capacitor-purchases/commit/b1b94da34ec268fb5c0291c6e7a9efa123888274) i think we fixed it

**Comment by arbassic** [comment]
Now it works correctly, thanks.

Closing the issue as resolved
