### ISSUE TITLE
login() not implemented on ios

### ISSUE THREAD

**Issue by eikaramba** [Cap-go/capacitor-purchases#37]
Hey there, i switched from https://github.com/RevenueCat/cordova-plugin-purchases to this plugin, but get the error `login() is not implemented on ios". Setup works however. But as far as the docs state, you should only call setup once and rather login() if you use a classical auth login/register schema.

Is this an oversight, should i just ignore it and call setup every time, although this might lead to multiple calls of setup() if the user logs out and logs in again?

**Comment by eikaramba** [comment]
i am on 2.0.15, so yes it should be the latest version. i actually never used an older version.

**Comment by riderx** [comment]
I think i got your issue did you use `logIn` or `login` ?
in the official SDK it's with the uppercase so i did the same

**Comment by eikaramba** [comment]
that was it! i could have sworn that i did try both variants but what can i say, logIn() is working! thank you, i will close this issue now :)
