### ISSUE TITLE
Add support for enableAdServicesAttributionTokenCollection() Method

### ISSUE THREAD

**Issue by dliver-more** [Cap-go/capacitor-purchases#54]
This method is used for the Apple Search Ads integration, and possibly others. It does not yet appear to be supported via the plugin. Details are here: 

https://www.revenuecat.com/docs/apple-search-ads#standard

**Comment by riderx** [comment]
Thanks for the report ! i just added it :
[2.1.0](https://github.com/Cap-go/capacitor-purchases/tree/2.1.0)

**Comment by dliver-more** [comment]
Awesome, thanks!
