### ISSUE TITLE
Capacitor 5 Support

### ISSUE THREAD

**Issue by felipeclopes** [Cap-go/capacitor-purchases#66]
I would like to request support for Capacitor 5.

As you may be aware, Capacitor 5 has been released with significant updates and improvements. It would be highly beneficial if this plugin could be updated to support Capacitor 5 and its features.

If you require any further information or assistance, please let me know. I would be happy to provide any additional details or collaborate in any way that can facilitate the update process.

Thank you for your attention to this matter. I look forward to your response and the possibility of seeing Capacitor 5 support.

**Comment by riderx** [comment]
Hey @felipeclopes i'm currently a bit busy but if you want you can create a PR and follow the guide ionic provided, for upgrading the plugin, i will accept the PR

**Comment by riderx** [comment]
The v5 has been released
