### ISSUE TITLE
Migrate IOS to purchases-hybrid-common V3 instead of custom integration

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-purchases#7]
The current integration is custom-made because purchases-hybrid-common was not ready for the latest RevenueCat SDK, since it's not a problem anymore it's better to migrate to purchases-hybrid-common for better compatibility 
https://github.com/RevenueCat/purchases-hybrid-common/releases

**Comment by productdevbook** [comment]
Is there a plan about this, when will the transition be made.

**Comment by riderx** [comment]
it's on my tasklist, i will try to look next week

**Comment by riderx** [comment]
It's done !
