### ISSUE TITLE
RevenueCat official transfer

### ISSUE THREAD

**Issue by chrisk-7777** [Cap-go/capacitor-purchases#76]
I've seen it mentioned in a few issues, but is there any news about this being officially rolled into the RevenueCat org? 

You've done a great job getting this far, but I'm just weighing up longevity of the project. For example in [this issue](https://github.com/Cap-go/capacitor-purchases/issues/66) you mentioned you're a bit busy, which is 100% understandable, but considering RevenueCat is a paid/premium product having this repo officially backed/supported would be preferred from a business perspective. 

Do you have a contact at RevenueCat who is looking after the connection with this repo? 

Thanks for the library

**Comment by riderx** [comment]
Hey @chrisk-7777 the plugin has been updated to capacitor 5, 2 weeks ago so less than 15 days after the issue creation.
I'm doing my best to support all necessary evolution, until migration is done.

RevenueCat discussions are ongoing, we have agreement, we just need a bit more time.

They have access in writing to this repo and are able to make fix if needed.

Lastly this plugin use RevenueCat PurchasesHybridCommon it hadle 90% of the job.
The same base as all others of they component: cordova, react native, etc.

I didn't fixed the dependency version, when they publish fix you got it next time you do a `npx cap sync`.

For all this reason i think you shouldn't be worried about the lib.

RevenueCat and Capgo (me) are commited to keep this lib healthy, and good for users.

**Comment by chrisk-7777** [comment]
Thanks for your work @riderx and commitment to this project. I missed that the v5 release had been tag (there was no mention of it in the linked issue). 

I understand what you mean and appreciate your efforts.

**Comment by riderx** [comment]
Yep you are right i will update it

**Comment by chrisk-7777** [comment]
Thanks @riderx ! This project has been a life saver for my current project

**Comment by riderx** [comment]
Me too, one of my app make $700 a month because of amazing work of RevenueCat i was able to integrate super fast !
Thanks a lot for the feedback <3
