### ISSUE TITLE
Capacitor vs. Cordova Version

### ISSUE THREAD

**Issue by mariusbolik** [Cap-go/capacitor-purchases#85]
Hello,

thank you for creating this awesome plugin! What are the advantages of using this Plugin instead of using the cordova version?

Kind Regards,
Marius

**Comment by riderx** [comment]
Usually Cordova plugin are a bit messy to use and config compare to capacitor native one.
Like you need ionic lib + Cordova one for reactivity. Here only capacitor.
But both are valid, plus this one will become officially supported by Revenue Cat soon

**Comment by mariusbolik** [comment]
Thank you! Will the officially supported Capacitor plugin have the getProducts method?

**Comment by riderx** [comment]
i did added it today here so yes it will as that one have it too now :)

**Comment by mariusbolik** [comment]
Thank you very much for your work! I really appreciate it!
