### ISSUE TITLE
Deprecated with Capacitor 5?

### ISSUE THREAD

**Issue by diegoextendi** [Cap-go/capacitor-purchases#88]
After updating Capactitor to v5 I get this message in VS Code:

`@capgo/capacitor-purchases: @capgo/capacitor-purchases is deprecated: Go back to v5, this version was send by CI/CD fantaisy, sorry for this`

Don't understand what this means, can you explain?

**Comment by riderx** [comment]
Sorry agree the message is not clear.
The CI/CD got crazy and started to release a major version each time I sent a minor fix.
So the right version number is `5.1.0` if your plugin is higher, you are on a broken/deprecated version.

**Comment by diegoextendi** [comment]
Oh ok! Yes that was a weird message :) ok it's fine, VS Code already proposed to downgrade from 10.0.0 to 5.0.8, I'll upgrade to 5.1.0
